name: Build and Push FE & BE to ECR  

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ---- Frontend ----
      - name: Build and Push Frontend
        working-directory: ./client
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ secrets.ECR_FE_REPO }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_FE_REPO }}:$IMAGE_TAG

      # ---- Backend ----
      - name: Build and Push Backend
        working-directory: ./api
        run: |
          IMAGE_TAG=latest
          docker build -t ${{ secrets.ECR_BE_REPO }}:$IMAGE_TAG .
          docker push ${{ secrets.ECR_BE_REPO }}:$IMAGE_TAG
